server:
  port: 8082

spring:
  application:
    name: kafkaConsumer
  kafka:
    bootstrap-servers: "[::1]:9092"
  mail:
    host: smtp.gmail.com
    port: 587
    username: sendingTesting123
    password: testing123!
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka