spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: movie
          uri: lb://MOVIE
          predicates:
            - Path=/api/movie/**
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka